version: '3'
services:
  ibrahim-tarigan:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ibrahimtrg18/ibrahim-tarigan
    container_name: ibrahim-tarigan
    command: ["yarn", "start", "-p", "8080"]
    ports:
      - 8080:8080
    volumes:
      - ibrahim-tarigan:/home/ibrahim-tarigan
    networks:
      - nginx_network

volumes:
  ibrahim-tarigan:
    external: true

networks:
  nginx_network:
    external: true
