version: '3'
services:
  me:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ibrahimtrg18/me
    container_name: me
    ports:
      - 8080:8080
    networks:
      - webserver

networks:
  webserver:
    external: true