# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GATSBY_GOOGLE_MAPS_API_KEY: ${{ secrets.GATSBY_GOOGLE_MAPS_API_KEY }}
  GATSBY_GETFORMIO_ENDPOINT: ${{ secrets.GATSBY_GETFORMIO_ENDPOINT }}

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js '16.13.1'
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build --if-present

      - name: Delete existing files
        run: rm -rf /var/www/ibrahimtarigan.me/html/*

      - name: Move builded folder
        run: mv /root/cicd/ibrahim-tarigan/_work/ibrahim-tarigan/ibrahim-tarigan/public/* /var/www/ibrahimtarigan.me/html
